package cli

import (
	"context"
	"fmt"
	"log/slog"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/ny4rl4th0t3p/seedward-gentool/pkg/config"
	"github.com/ny4rl4th0t3p/seedward-gentool/pkg/genesis"
	"github.com/ny4rl4th0t3p/seedward-gentool/pkg/genesis/csv"
	"github.com/ny4rl4th0t3p/seedward-gentool/pkg/genesis/encoding"
	"github.com/ny4rl4th0t3p/seedward-gentool/pkg/genesis/gentx"
)

const (
	flagConfig       = "config"
	flagInputGenesis = "input-genesis"
)

// NewGenesisCommands returns gentool's genesis commands as fresh, self-contained
// instances — every flag they read is declared on the commands themselves, so
// they can be mounted under an arbitrary parent. This is the embedding API.
//
// The commands own a --config flag. A host CLI must not declare a persistent
// flag of the same name: cobra resolves the collision silently in favor of
// these commands, so the host's flag becomes unreachable (and never populated)
// for any invocation through this subtree.
func NewGenesisCommands() []*cobra.Command {
	return []*cobra.Command{newCreateCmd()}
}

func newCreateCmd() *cobra.Command {
	// Per-command viper instance: config state lives in this command, never in
	// the global singleton a host CLI may be using.
	v := viper.New()

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a genesis file from a baseline genesis and CSV inputs",
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			cfgFile, err := cmd.Flags().GetString(flagConfig)
			if err != nil {
				return err
			}
			initConfig(v, cfgFile)
			return nil
		},
		RunE: func(cmd *cobra.Command, _ []string) error {
			inputGenesis, err := cmd.Flags().GetString(flagInputGenesis)
			if err != nil || inputGenesis == "" {
				return fmt.Errorf("--input-genesis is required: path to a baseline genesis file from '<chaind> init'")
			}

			inputs, err := config.FromViper(v)
			if err != nil {
				return err
			}
			cfg := inputs.Chain
			hrp := cfg.AddressPrefix

			raw, err := os.ReadFile(inputGenesis)
			if err != nil {
				return fmt.Errorf("failed to read --input-genesis %s: %w", inputGenesis, err)
			}

			moduleAddresses := computeAllModuleAddresses(hrp, cfg.ExtraModules)

			repos := genesis.Repositories{
				Claims:          csv.NewCSVClaimRepository(inputs.Claims, moduleAddresses),
				Grants:          csv.NewCSVGrantRepository(inputs.Grants, moduleAddresses),
				InitialAccounts: csv.NewCSVInitialAccountsRepository(inputs.Accounts, moduleAddresses),
				Validators:      gentx.NewValidatorRepository(inputs.GentxDir, hrp),
			}
			// authz/feegrant are optional: an unset path signals "module not configured".
			if inputs.Authz != "" {
				repos.AuthzGrants = csv.NewCSVAuthzGrantRepository(inputs.Authz, moduleAddresses)
			}
			if inputs.Feegrant != "" {
				repos.FeeAllowances = csv.NewCSVFeeAllowanceRepository(inputs.Feegrant, moduleAddresses)
			}

			appGenesis, err := genesis.Build(context.Background(), raw, cfg, repos)
			if err != nil {
				slog.Error(err.Error())
				return err
			}

			return appGenesis.SaveAs(v.GetString("genesis.output"))
		},
	}

	cmd.Flags().String(flagConfig, "", "config file (default is ./.gentool.yaml)")
	cmd.Flags().String(flagInputGenesis, "", "Path to baseline genesis file generated by '<chaind> init' (required)")

	return cmd
}

// initConfig loads the config file (or ./.gentool.yaml) and env overrides into
// the command's own viper instance.
func initConfig(v *viper.Viper, cfgFile string) {
	if cfgFile != "" {
		v.SetConfigFile(cfgFile)
	} else {
		v.AddConfigPath(".")
		v.SetConfigType("yaml")
		v.SetConfigName(".gentool")
	}

	v.AutomaticEnv()

	if err := v.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", v.ConfigFileUsed())
	}
}

func computeAllModuleAddresses(hrp string, extraModules []genesis.ExtraModule) map[string]bool {
	names := make([]string, 0, len(encoding.StandardModuleNames)+len(extraModules))
	names = append(names, encoding.StandardModuleNames...)
	for _, em := range extraModules {
		names = append(names, em.Name)
	}
	return encoding.ModuleAddresses(hrp, names)
}
