package cli

import (
	"context"
	"fmt"
	"log/slog"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/pkg/genesis"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/pkg/genesis/csv"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/pkg/genesis/encoding"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/pkg/genesis/gentx"
)

const (
	flagConfig       = "config"
	flagInputGenesis = "input-genesis"
)

// NewGenesisCommands returns gentool's genesis commands as fresh, self-contained
// instances — every flag they read is declared on the commands themselves, so
// they can be mounted under an arbitrary parent. This is the embedding API.
//
// The commands own a --config flag. A host CLI must not declare a persistent
// flag of the same name: cobra resolves the collision silently in favor of
// these commands, so the host's flag becomes unreachable (and never populated)
// for any invocation through this subtree.
func NewGenesisCommands() []*cobra.Command {
	return []*cobra.Command{newCreateCmd()}
}

func newCreateCmd() *cobra.Command {
	// Per-command viper instance: config state lives in this command, never in
	// the global singleton a host CLI may be using.
	v := viper.New()

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a genesis file from a baseline genesis and CSV inputs",
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			cfgFile, err := cmd.Flags().GetString(flagConfig)
			if err != nil {
				return err
			}
			initConfig(v, cfgFile)
			return nil
		},
		RunE: func(cmd *cobra.Command, _ []string) error {
			inputGenesis, err := cmd.Flags().GetString(flagInputGenesis)
			if err != nil || inputGenesis == "" {
				return fmt.Errorf("--input-genesis is required: path to a baseline genesis file from '<chaind> init'")
			}

			hrp := v.GetString("chain.address_prefix")
			if hrp == "" {
				return fmt.Errorf("chain.address_prefix is required in config")
			}
			cfg := buildChainConfig(v, hrp)

			raw, err := os.ReadFile(inputGenesis)
			if err != nil {
				return fmt.Errorf("failed to read --input-genesis %s: %w", inputGenesis, err)
			}

			moduleAddresses := computeAllModuleAddresses(hrp, cfg.ExtraModules)

			repos := genesis.Repositories{
				Claims:          csv.NewCSVClaimRepository(v.GetString("claims.file_name"), moduleAddresses),
				Grants:          csv.NewCSVGrantRepository(v.GetString("grants.file_name"), moduleAddresses),
				InitialAccounts: csv.NewCSVInitialAccountsRepository(v.GetString("accounts.file_name"), moduleAddresses),
				Validators:      gentx.NewValidatorRepository(v.GetString("validators.gentx_dir"), hrp),
			}
			// authz/feegrant are optional: a nil repository signals "module not configured".
			if v.IsSet("authz.file_name") {
				repos.AuthzGrants = csv.NewCSVAuthzGrantRepository(v.GetString("authz.file_name"), moduleAddresses)
			}
			if v.IsSet("feegrant.file_name") {
				repos.FeeAllowances = csv.NewCSVFeeAllowanceRepository(v.GetString("feegrant.file_name"), moduleAddresses)
			}

			appGenesis, err := genesis.Build(context.Background(), raw, cfg, repos)
			if err != nil {
				slog.Error(err.Error())
				return err
			}

			return appGenesis.SaveAs(v.GetString("genesis.output"))
		},
	}

	cmd.Flags().String(flagConfig, "", "config file (default is ./.gentool.yaml)")
	cmd.Flags().String(flagInputGenesis, "", "Path to baseline genesis file generated by '<chaind> init' (required)")

	return cmd
}

// initConfig loads the config file (or ./.gentool.yaml) and env overrides into
// the command's own viper instance.
func initConfig(v *viper.Viper, cfgFile string) {
	if cfgFile != "" {
		v.SetConfigFile(cfgFile)
	} else {
		v.AddConfigPath(".")
		v.SetConfigType("yaml")
		v.SetConfigName(".gentool")
	}

	v.AutomaticEnv()

	if err := v.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", v.ConfigFileUsed())
	}
}

// buildChainConfig assembles the genesis.ChainConfig from viper. This is the single
// place viper is read for genesis construction; the genesis package takes the struct.
func buildChainConfig(v *viper.Viper, hrp string) genesis.ChainConfig {
	type extraModuleConfig struct {
		Name        string   `mapstructure:"name"`
		Permissions []string `mapstructure:"permissions"`
	}
	var raw []extraModuleConfig
	_ = v.UnmarshalKey("modules.extra", &raw)
	extra := make([]genesis.ExtraModule, 0, len(raw))
	for _, em := range raw {
		extra = append(extra, genesis.ExtraModule{Name: em.Name, Permissions: em.Permissions})
	}

	return genesis.ChainConfig{
		ChainID:       v.GetString("chain.id"),
		AppName:       v.GetString("app.name"),
		AppVersion:    v.GetString("app.version"),
		GenesisTime:   v.GetInt64("app.genesis_time"),
		InitialHeight: v.GetInt64("chain.initial_height"),

		AddressPrefix: hrp,
		BondDenom:     v.GetString("default_bond_denom"),

		TotalSupply:     v.GetInt64("accounts.total_supply"),
		NonStakedAmount: v.GetInt64("accounts.non_staked_amount"),

		ClaimsVestingEnd:   v.GetInt64("claims.vesting.end_date"),
		GrantsVestingStart: v.GetInt64("grants.vesting.start_date"),
		GrantsVestingEnd:   v.GetInt64("grants.vesting.end_date"),

		DenomBase:        v.GetString("denom.base"),
		DenomDisplay:     v.GetString("denom.display"),
		DenomSymbol:      v.GetString("denom.symbol"),
		DenomDescription: v.GetString("denom.description"),
		DenomExponent:    v.GetUint32("denom.exponent"),
		DenomAliases:     v.GetStringSlice("denom.aliases"),

		ExtraModules: extra,

		UnbondingTimeSeconds: v.GetInt64("chain.unbonding_time_seconds"),
		MaxValidators:        v.GetUint32("chain.max_validators"),
		MaxEntries:           v.GetUint32("chain.max_entries"),
		HistoricalEntries:    v.GetUint32("chain.historical_entries"),
		MinCommissionRate:    v.GetString("chain.min_commission_rate"),

		BlocksPerYear:       v.GetInt64("chain.blocks_per_year"),
		InflationRateChange: v.GetString("chain.inflation_rate_change"),
		InflationMax:        v.GetString("chain.inflation_max"),
		InflationMin:        v.GetString("chain.inflation_min"),
		GoalBonded:          v.GetString("chain.goal_bonded"),

		GovMinDepositAmount:          v.GetInt64("gov.min_deposit_amount"),
		GovVotingPeriod:              v.GetString("gov.voting_period"),
		GovExpeditedMinDepositAmount: v.GetInt64("gov.expedited_min_deposit_amount"),
		GovExpeditedVotingPeriod:     v.GetString("gov.expedited_voting_period"),

		SignedBlocksWindow:          v.GetInt64("slashing.signed_blocks_window"),
		MinSignedPerWindow:          v.GetString("slashing.min_signed_per_window"),
		DowntimeJailDurationSeconds: v.GetInt64("slashing.downtime_jail_duration_seconds"),
		SlashFractionDoubleSign:     v.GetString("slashing.slash_fraction_double_sign"),
		SlashFractionDowntime:       v.GetString("slashing.slash_fraction_downtime"),

		CommunityPoolAmount: v.GetInt64("distribution.community_pool_amount"),
	}
}

func computeAllModuleAddresses(hrp string, extraModules []genesis.ExtraModule) map[string]bool {
	names := make([]string, 0, len(encoding.StandardModuleNames)+len(extraModules))
	names = append(names, encoding.StandardModuleNames...)
	for _, em := range extraModules {
		names = append(names, em.Name)
	}
	return encoding.ModuleAddresses(hrp, names)
}
