package cmd

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/cosmos/cosmos-sdk/server"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/internal/app"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/internal/encoding"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/internal/repository/csv"
	"github.com/ny4rl4th0t3p/cosmos-genesis-tool/internal/repository/gentx"
)

const flagInputGenesis = "input-genesis"

var createCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a genesis file from a baseline genesis and CSV inputs",
	RunE: func(cmd *cobra.Command, _ []string) error {
		inputGenesis, err := cmd.Flags().GetString(flagInputGenesis)
		if err != nil || inputGenesis == "" {
			return fmt.Errorf("--input-genesis is required: path to a baseline genesis file from '<chaind> init'")
		}

		// Configure global SDK state before any address encoding occurs.
		hrp := viper.GetString("chain.address_prefix")
		if hrp == "" {
			return fmt.Errorf("chain.address_prefix is required in config")
		}
		sdkConfig := sdk.GetConfig()
		sdkConfig.SetBech32PrefixForAccount(hrp, hrp+"pub")
		sdkConfig.SetBech32PrefixForValidator(hrp+"valoper", hrp+"valoperpub")
		sdkConfig.SetBech32PrefixForConsensusNode(hrp+"valcons", hrp+"valconspub")
		sdkConfig.Seal()

		sdk.DefaultBondDenom = viper.GetString("default_bond_denom")

		encodingConfig, clientCtx, appGenState, appGenesis, err := app.LoadGenesis(inputGenesis)
		if err != nil {
			return err
		}

		cometConfig := server.GetServerContextFromCmd(cmd).Config
		cometConfig.SetRoot(".")

		moduleAddresses := computeAllModuleAddresses(hrp)

		claimRepository := csv.NewCSVClaimRepository(viper.GetString("claims.file_name"), moduleAddresses)
		grantRepository := csv.NewCSVGrantRepository(viper.GetString("grants.file_name"), moduleAddresses)
		initialAccountsRepository := csv.NewCSVInitialAccountsRepository(viper.GetString("accounts.file_name"), moduleAddresses)
		validatorsRepository := gentx.NewValidatorRepository(viper.GetString("validators.gentx_dir"))
		authzGrantRepository := csv.NewCSVAuthzGrantRepository(viper.GetString("authz.file_name"), moduleAddresses)
		feeAllowanceRepository := csv.NewCSVFeeAllowanceRepository(viper.GetString("feegrant.file_name"), moduleAddresses)

		appStateManager := app.NewAppStateManager(
			claimRepository,
			grantRepository,
			initialAccountsRepository,
			validatorsRepository,
			authzGrantRepository,
			feeAllowanceRepository,
			appGenState,
			appGenesis,
			encodingConfig,
			cometConfig,
			clientCtx,
		)

		appGenesis, shares, err := appStateManager.SetupAppState(context.Background())
		if err != nil {
			slog.Error(err.Error())
			return err
		}

		consensus := app.NewConsensus(validatorsRepository, appGenesis, encodingConfig.TxConfig.SigningContext().AddressCodec(), shares)
		if err = consensus.SetParams(); err != nil {
			return err
		}

		return appGenesis.SaveAs(viper.GetString("genesis.output"))
	},
}

func computeAllModuleAddresses(hrp string) map[string]bool {
	type extraModuleConfig struct {
		Name string `mapstructure:"name"`
	}
	var extraModules []extraModuleConfig
	_ = viper.UnmarshalKey("modules.extra", &extraModules)

	names := make([]string, 0, len(encoding.StandardModuleNames)+len(extraModules))
	names = append(names, encoding.StandardModuleNames...)
	for _, em := range extraModules {
		names = append(names, em.Name)
	}
	return encoding.ModuleAddresses(hrp, names)
}

func init() {
	rootCmd.AddCommand(createCmd)
	createCmd.Flags().String(flagInputGenesis, "", "Path to baseline genesis file generated by '<chaind> init' (required)")
}
